### ISSUE TITLE
Sibling lessons merge and lesson changes implementation

### ISSUE THREAD

**Issue by phy25** [LangleyChang/onChart#2]
-  If there are same classes in a row (In the morning, class 1-2: Economy, class 3-4: Economy), maybe the app can merge them.
-  If there are class changes, read it and present the changes (may include deletion, addition and modification).

You may be interested to see this: https://github.com/phy25/bPlanner/blob/master/includes/schoolBITclass.php

**Comment by zhehuaz** [comment]
I wonder why you use 8 space indentation.Looks really bent、

**Comment by phy25** [comment]
Hasn't noticed that. I will make them the same. Actually I prefer to use tabs...

**Comment by zhehuaz** [comment]
You mean there is a case that one period of a class split into two blocks in timetable?

**Comment by phy25** [comment]
![screenshot_2016-01-12-08-56-50](https://cloud.githubusercontent.com/assets/331403/12349244/0bbd1184-bba9-11e5-8485-f3db0d49e760.png)

P.S. I don't know this person...

**Comment by zhehuaz** [comment]
I'll fix them in winter holiday...

**Comment by zhehuaz** [comment]
In class changes, I find some strange items,
![screenshot1](https://cloud.githubusercontent.com/assets/6506398/12484410/2c4e47c4-c095-11e5-9997-59b1055ee2e6.png)
![screenshot2](https://cloud.githubusercontent.com/assets/6506398/12484491/8374d806-c095-11e5-8811-d2ec54bd4e9a.png)
of which classrooms are missed.
And some even aren't consistent.
Thus, I decide to refactor the app and support more flexible operations, like modifying the table manually.

**Comment by phy25** [comment]
You can refer to the code below. It is objective, and handles many cases because I have fed it with many different major's infomation (including null location after changes, more than one change to a specific schedule). If you need those example accounts, email me.

**Comment by zhehuaz** [comment]
That's excellent, thanks.
I'll refactor it ASAP to support dynamic timetable.

**Comment by zhehuaz** [comment]
And about the different interchange cases, would you like to work on a wiki in your repo?
I think it's the best way to collect the information.

**Comment by phy25** [comment]
Good idea. Just after exams...

**Comment by phy25** [comment]
Docs / guide: https://github.com/phy25/bPlanner/wiki/

Contributions on the wiki are welcome, like examples.

**Comment by zhehuaz** [comment]
Nice job.
Or I can close the issue now.
